language: java
addons:
  sonarcloud:
    organization: "lvcarnevalli-github"

install: true
script: mvn clean verify -B -V
after_success: mvn sonar:sonar -B

deploy:
  provider: script
  script:
    - openssl aes-256-cbc -K $encrypted_a1fc9919b14a_key -iv $encrypted_a1fc9919b14a_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d && tar xvf travis/secrets.tar -C travis/
    - mvn deploy -B --settings travis/settings.xml -DperformRelease=true
  skip_cleanup: true
  on:
    tags: true