language: java
addons:
  sonarcloud:
    organization: "lvcarnevalli-github"
before_install:
  openssl aes-256-cbc -K $encrypted_a1fc9919b14a_key -iv $encrypted_a1fc9919b14a_iv -in travis/secret_key.gpg.enc -out travis/secret_key.gpg -d
install:
  - mvn clean verify -B -V
after_success:
  - mvn sonar:sonar -B

deploy:
  provider: script
  script:
    - mvn deploy -B --settings travis/settings.xml -DperformRelease=true -DskipTests=true
  skip_cleanup: true
  on:
    tags: true