language: java
addons:
  sonarcloud:
    organization: "lvcarnevalli-github"

install:
  - mvn clean install
script:
  - cd examples
  - sh run.sh
after_success:
  - cd ..
  - mvn verify sonar:sonar -B

deploy:
  provider: script
  skip_cleanup: true
  script: sh travis/deploy.sh
#  on:
#    tags: true