language: java
addons:
  sonarcloud:
    organization: "lvcarnevalli-github"

install: true
script: mvn clean verify -B -V -Dtarget.url="http://$(ip -4 addr show scope global | grep inet | awk '{print $2}' | cut -d / -f 1):9000"
after_success: mvn sonar:sonar -B

deploy:
  provider: script
  skip_cleanup: true
  script: sh travis/deploy.sh
  on:
    tags: true