language: java
addons:
  sonarcloud:
    organization: "lvcarnevalli-github"

install: true
script: mvn clean verify -B -V
after_success: mvn sonar:sonar -B

deploy:
  provider: script
  skip_cleanup: true
  script: sh travis/deploy.sh
  on:
    tags: true